org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true

launchpad_version=1.9.2
minecraft_version=26.2
neo_version=26.2.0.88

## Mod Properties

mod_id=launchpad
mod_name=Launchpad
mod_license=GNU GPL v3 only, with the Classpath Exception v2.0
mod_license_spdx=GPL-3.0-only WITH Classpath-exception-2.0
mod_group_id=org.sinytra.launchpad

## Publishing

compatible_versions=26.2
curseforge_id=1584761
modrinth_id=voWgQoWV
github_repo=Sinytra/Launchpad

# This is the branch the release tag will be created from
publish_branch=master
