[plugins]
moddev = { id = "net.neoforged.moddev", version = "2.0.141" }
shadow = { id = "com.gradleup.shadow", version = "9.4.2" }
gradleutils = { id = "net.neoforged.gradleutils", version = "5.1.1" }
publishing = { id = "me.modmuss50.mod-publish-plugin", version = "2.1.1" }
licenser = { id = "net.neoforged.licenser", version = "0.7.5" }

[libraries]
forgified-fabric-api = { group = "org.sinytra.forgified-fabric-api", name = "forgified-fabric-api", version = "0.161.0+26.2+4.0.0" }
forgified-fabric-loader = { group = "org.sinytra", name = "forgified-fabric-loader", version = "2.5.86+0.19.3+26.2" }
clazz-tweaker = { group = "net.fabricmc", name = "class-tweaker", version = "0.3.0" }

junit-jupiter = { group = "org.junit.jupiter", name = "junit-jupiter", version = "5.7.1" }
junit-platform-launcher = { group = "org.junit.platform", name = "junit-platform-launcher" }
testframework = { group = "net.neoforged", name = "testframework", version = "26.2.0.88" }
